### ISSUE TITLE
Not able to stop the script. "Control+C" also not working.

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/wifi-deauth-attack#1]
Because, each thread(non-daemonised) runs infinite loop, it is difficult to stop the script("Control+C" also not working.). 

**Work Around**: 

press `Control+Z` and kill explicitly kill `ps aux | grep deauth.py | awk '{print $2}'`
or
`sudo pkill -9 -f deauth.py `

**Comment by grr** [comment]
don't know python, but this might help with the problem:
https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true
