### ISSUE TITLE
does it work for macos?

### ISSUE THREAD

**Issue by CarlXK** [veerendra2/wifi-deauth-attack#8]

**Comment by veerendra2** [comment]
Not sure. Need to test.

**Comment by veerendra2** [comment]
If you have mac, can you run and paste the output if it is failing?

**Comment by CarlXK** [comment]
not work, seems can't create interface

`
wifi-deauth-attack git:(master) sudo python deauth.py
Password:

+----------------------------------------------------------------+
|Deauth v3.1                                                     |
|Coded by Veerendra Kakumanu (veerendra2)                        |
|Blog: https://veerendra2.github.io/wifi-deathentication-attack/ |
|Repo: https://github.com/veerendra2/wifi-deauth-attack          |
+----------------------------------------------------------------+

Traceback (most recent call last):
  File "deauth.py", line 282, in <module>
    Interface = CreatIface()
  File "deauth.py", line 95, in __init__
    self.readDevFile()
  File "deauth.py", line 112, in readDevFile
    with open(DEV_FILE) as f:
IOError: [Errno 2] No such file or directory: '/proc/net/dev'
➜  wifi-deauth-attack git:(master) sudo python deauth.py -m bc:5f:f6:0b:3c:4a

+----------------------------------------------------------------+
|Deauth v3.1                                                     |
|Coded by Veerendra Kakumanu (veerendra2)                        |
|Blog: https://veerendra2.github.io/wifi-deathentication-attack/ |
|Repo: https://github.com/veerendra2/wifi-deauth-attack          |
+----------------------------------------------------------------+

Traceback (most recent call last):
  File "deauth.py", line 282, in <module>
    Interface = CreatIface()
  File "deauth.py", line 95, in __init__
    self.readDevFile()
  File "deauth.py", line 112, in readDevFile
    with open(DEV_FILE) as f:
IOError: [Errno 2] No such file or directory: '/proc/net/dev'
`

**Comment by veerendra2** [comment]
Thanks for output. Looks like there is no `/proc/net/dev` dev file, the script gets the interface list from dev file. I don't know much about MAC OS. May be future version, will include support for MAC OS. :-)
